Notification about not empty category while deleting
tungyr-one/coding-tasks pull request #23
Opened 2023-03-24 15:27 UTC by tungyr-one

Let user know what he can lost

2023-03-24 15:40 UTC, coder1coder requested changes

2023-03-24 15:40 UTC, coder1coder commented on DocumentApp/ClientApp/src/app/doc-list/doc-list.component.ts
> +        console.log(error);
убрать console.log

2023-03-24 15:40 UTC, coder1coder commented on DocumentApp/api/Exceptions/ValidationsException.cs
> +    public class ValidationException: ArgumentException
Можно унаследовать просто от Exception

2023-03-24 15:40 UTC, coder1coder commented on DocumentApp/api/Services/CategoriesService.cs
> +        public CategoriesService(ICategoriesRepository categoryRepository, DataContext context, ILogger<CategoriesService> logger,
прокидывать DbContext только в репозиториях

2023-03-24 15:40 UTC, coder1coder commented on DocumentApp/api/Services/CategoriesService.cs
> +            if (await _context.Docs.AnyAsync(d => d.Category.Id == id))
Инкапсулировать в метод репозитория Exists

2023-03-26 09:55 UTC, tungyr-one commented on DocumentApp/api/Services/CategoriesService.cs
> +            if (await _context.Docs.AnyAsync(d => d.Category.Id == id))
Добавил метод в последнем коммите:
` async Task<bool> IDocsRepository.IsDocumentWithCategoryRelationExists(int categoryId)
        {
            return await _context.Docs.AnyAsync(d => d.Category.Id == categoryId);
        }
`

2023-03-26 09:55 UTC, tungyr-one commented on DocumentApp/ClientApp/src/app/doc-list/doc-list.component.ts
> +        console.log(error);
My bad

2023-03-26 09:55 UTC, tungyr-one commented on DocumentApp/api/Exceptions/ValidationsException.cs
> +    public class ValidationException: ArgumentException
Точно

2023-03-26 09:56 UTC, tungyr-one commented on DocumentApp/api/Services/CategoriesService.cs
> +        public CategoriesService(ICategoriesRepository categoryRepository, DataContext context, ILogger<CategoriesService> logger,
Запомню

2023-03-26 10:03 UTC, merged