Final changes
tungyr-one/coding-tasks pull request #24
Opened 2023-05-10 17:05 UTC by tungyr-one

2023-05-10 17:35 UTC, coder1coder requested changes

2023-05-10 17:35 UTC, coder1coder commented on DocumentApp/ClientApp/src/app/_models/FlatNode.ts
> +export interface FlatNode {
IFlatNode

2023-05-10 17:35 UTC, coder1coder commented on DocumentApp/api/Data/Repositories/CategoriesRepository.cs
> +            .ThenInclude(c => c.Children)
мм, сколько нужно ThenInclude для 5 уровневой схемы? :)

2023-05-10 17:35 UTC, coder1coder commented on DocumentApp/api/Helpers/AutoMapperProfiles.cs
> +                    opt => opt.MapFrom(src => DateTime.Now));
дата в UTC

2023-05-10 17:35 UTC, coder1coder commented on DocumentApp/api/Helpers/AutoMapperProfiles.cs
> +                    opt => opt.MapFrom(src => DateTime.Now));
UTC

2023-05-10 17:35 UTC, coder1coder commented on DocumentApp/api/Helpers/AutoMapperProfiles.cs
> +                    opt => opt.MapFrom(src => src.Version + 1))
не явная логика, лучше сделать это в методе сервиса

2023-05-10 17:35 UTC, coder1coder commented on DocumentApp/api/Helpers/Pagination.cs
> +            var items = await source.Skip(pageNumber * pageSize).Take(pageSize).ToArrayAsync();
А если надо будет добавить сортировку? 
Да и на бэке я бы принимал не номер страницы а offset - количество записей которое надо скипнуть. Пусть фронт решает как у него странички работают

2023-05-10 17:35 UTC, coder1coder commented on DocumentApp/api/Services/CategoriesService.cs
>            var categoryDb = await _categoriesRepository.GetCategoryAsync(id);
а если по идентификатору не найдется категория, что в таком случае?

2023-05-10 17:35 UTC, coder1coder commented on DocumentApp/api/Services/DocsService.cs
> +         switch(userParams.SortBy.ToLower())
Вот пример для сортировки:

        query = parameters.SortOrder == SortOrder.Asc
            ? query.OrderBy(ResolveOrderFieldExpression(parameters))
            : query.OrderByDescending(ResolveOrderFieldExpression(parameters));

private static Expression<Func<EventEntity, object>> ResolveOrderFieldExpression(PaginationSort parameters)
        => parameters.SortBy switch
        {
            nameof(EventEntity.Name) => x => x.Name,
            nameof(EventEntity.Start) => x => x.Start,
            nameof(EventEntity.Status) => x => x.Status,
            _ => x => x.Id
        };

2023-05-10 19:57 UTC, tungyr-one commented on DocumentApp/api/Data/Repositories/CategoriesRepository.cs
> +            .ThenInclude(c => c.Children)
Четыре, я полагаю. В моем случае возможна только 3 уровневая иерархия и пользователь не сможет создать более глубокую

2023-05-11 08:21 UTC, tungyr-one commented on DocumentApp/api/Helpers/Pagination.cs
> +            var items = await source.Skip(pageNumber * pageSize).Take(pageSize).ToArrayAsync();
Сортировка происходит в методе сервиса, а в классе pagination уже определяется количество доков под страницу

2023-06-03 08:43 UTC, coder1coder requested changes

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Controllers/DocsController.cs
> +         .SerializeObject(new
мм, а зачем оно тут? 
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponsejsonextensions.writeasjsonasync?view=aspnetcore-6.0

необходимо исключить любое упоминание Newtonsoft.Json в решении

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Controllers/DocsController.cs
>           return BadRequest("Failed to update document");
Унести проверку в метод сервиса, там и проверять значение из репозитория и бросать исключение.
Методы контроллера должны быть максимально простыми и не содержать условий валидации

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/DTOs/DocDto.cs
> +        public DateTime Edited { get; set; }
это поле должно поддерживать NULL

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/DTOs/UserParams.cs
> +    public class UserParams
надо добавить саммари

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Data/Repositories/CategoriesRepository.cs
>        public async Task<CategoryDb[]> GetCategoriesAsync()
Предлагаю сделать так.

`public Task<CategoryDb[]> GetCategoriesAsync() =>
           _context.Categories
           .AsNoTracking()
           .ToArrayAsync();`

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Data/Repositories/DocsRepository.cs
>          {
А в чем потребность вернуть IQueryable? Лучше так не делать. Если можно убрать - убери

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Entities/DocDb.cs
> +        public DateTime Edited { get; set; }
Может быть null

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Helpers/AutoMapperProfiles.cs
> +                    opt => opt.MapFrom(src => DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc)));
почему не DateTime.UtcNow ?

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Helpers/Pagination.cs
> +        public static async Task<Pagination<T>> CreateAsync(IQueryable<T> source, int offset, int pageSize)
давай переименуем в ToPageResult например или что-то подобное. CreateAsync слишком абстрактно

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Services/CategoriesService.cs
> +          return await _categoriesRepository.Create(categoryToDb);
_categoriesRepository.CreateAsync

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Services/CategoriesService.cs
> +            throw new ValidationException("Can't find category for update");
Если что-то не найдено то надо вернут 404 а не 400

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Services/CategoriesService.cs
> +            throw new ValidationException("Can't find category for update");
Это не проблема валидации данных, это проблема отсутствия сущности

2023-06-03 08:43 UTC, coder1coder commented on DocumentApp/api/Services/DocsService.cs
> +         userParams.SortBy = string.Concat(userParams.SortBy[0].ToString().ToUpper(), userParams.SortBy.AsSpan(1));
шо за магия? нипанятна! алярм!

вынеси в отдельный приватный метод с понятным наименованием :)

2023-09-04 10:13 UTC, merged